# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/prototype_watchman/prototype_watchman.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman || ORIG_REF_NAME==prototype_watchman} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_processing_system7_0_1/prototype_watchman_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_processing_system7_0_1 || ORIG_REF_NAME==prototype_watchman_processing_system7_0_1} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_ps7_0_axi_periph_1/prototype_watchman_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_ps7_0_axi_periph_1 || ORIG_REF_NAME==prototype_watchman_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_rst_ps7_0_100M_1/prototype_watchman_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_rst_ps7_0_100M_1 || ORIG_REF_NAME==prototype_watchman_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_ten_reg_map_0_1/prototype_watchman_ten_reg_map_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_ten_reg_map_0_1 || ORIG_REF_NAME==prototype_watchman_ten_reg_map_0_1} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_auto_pc_0/prototype_watchman_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_auto_pc_0 || ORIG_REF_NAME==prototype_watchman_auto_pc_0} -quiet] -quiet

# XDC: bd/prototype_watchman/prototype_watchman_ooc.xdc
