# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/prototype_watchman/prototype_watchman.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman || ORIG_REF_NAME==prototype_watchman} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_processing_system7_0_0/prototype_watchman_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_processing_system7_0_0 || ORIG_REF_NAME==prototype_watchman_processing_system7_0_0} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_axi_interconnect_0_1/prototype_watchman_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_axi_interconnect_0_1 || ORIG_REF_NAME==prototype_watchman_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_xlconcat_0_0/prototype_watchman_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_xlconcat_0_0 || ORIG_REF_NAME==prototype_watchman_xlconcat_0_0} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_axi_dma_0_0/prototype_watchman_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_axi_dma_0_0 || ORIG_REF_NAME==prototype_watchman_axi_dma_0_0} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_ps7_0_axi_periph_0/prototype_watchman_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_ps7_0_axi_periph_0 || ORIG_REF_NAME==prototype_watchman_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_rst_ps7_0_100M_0/prototype_watchman_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_rst_ps7_0_100M_0 || ORIG_REF_NAME==prototype_watchman_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_xlconstant_0_0/prototype_watchman_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_xlconstant_0_0 || ORIG_REF_NAME==prototype_watchman_xlconstant_0_0} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_example_0_0/prototype_watchman_example_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_example_0_0 || ORIG_REF_NAME==prototype_watchman_example_0_0} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_auto_pc_1/prototype_watchman_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_auto_pc_1 || ORIG_REF_NAME==prototype_watchman_auto_pc_1} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_xbar_1/prototype_watchman_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_xbar_1 || ORIG_REF_NAME==prototype_watchman_xbar_1} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_auto_pc_0/prototype_watchman_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_auto_pc_0 || ORIG_REF_NAME==prototype_watchman_auto_pc_0} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_auto_us_1/prototype_watchman_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_auto_us_1 || ORIG_REF_NAME==prototype_watchman_auto_us_1} -quiet] -quiet

# IP: bd/prototype_watchman/ip/prototype_watchman_auto_us_0/prototype_watchman_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prototype_watchman_auto_us_0 || ORIG_REF_NAME==prototype_watchman_auto_us_0} -quiet] -quiet

# XDC: bd/prototype_watchman/prototype_watchman_ooc.xdc
