# ----------------------------------------------------------------------------
# TIMING Constraint File
# ----------------------------------------------------------------------------


set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[0]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[1]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[2]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[12]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[13]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[14]}]
set_property MARK_DEBUG true [get_nets base_zynq_i/FifoManagerV4_0/CLK]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[23]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[25]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[29]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[30]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[31]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[11]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[16]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[7]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[27]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[28]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[8]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[10]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[4]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[3]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[5]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[6]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[9]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[17]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[18]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[19]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[20]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[21]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[15]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[26]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[22]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/DataOut[24]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[60]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[23]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[40]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[9]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[1]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[19]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[55]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[2]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[6]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[14]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[16]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[27]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[31]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[3]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[5]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[6]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[4]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[5]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[45]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[4]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[8]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[42]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[8]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[50]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[30]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[10]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[51]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[53]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[8]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[39]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[43]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[25]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[2]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[7]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[28]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[3]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[61]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[9]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[35]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[38]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[48]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[52]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[54]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[57]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[1]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[37]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[41]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[2]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[22]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[47]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[63]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[11]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[3]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[2]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[36]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[5]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[9]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[5]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[7]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[1]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[21]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[20]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[15]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[18]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[24]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[29]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[33]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[0]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[4]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[7]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[13]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[0]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[32]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[58]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[6]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[12]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[8]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[10]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[11]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[0]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[17]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[49]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[6]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[26]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[44]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[46]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[62]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[0]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[7]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[1]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[4]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[3]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[56]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[34]}]
set_property MARK_DEBUG true [get_nets {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[59]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list base_zynq_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 9 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[0]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[1]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[2]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[3]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[4]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[5]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[6]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[7]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_WdoAddr[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[0]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[1]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[2]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[3]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[4]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[5]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[6]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[7]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[8]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[9]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[10]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[11]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[12]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[13]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[14]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[15]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[16]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[17]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[18]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[19]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[20]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[21]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[22]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[23]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[24]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[25]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[26]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[27]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[28]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[29]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[30]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[31]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[32]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[33]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[34]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[35]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[36]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[37]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[38]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[39]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[40]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[41]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[42]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[43]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[44]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[45]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[46]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[47]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[48]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[49]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[50]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[51]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[52]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[53]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[54]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[55]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[56]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[57]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[58]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[59]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[60]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[61]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[62]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Time[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[0]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[1]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[2]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[3]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[4]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[5]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[6]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[7]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[8]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[9]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[10]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_TrigInfo[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 10 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[0]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[1]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[2]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[3]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[4]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[5]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[6]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[7]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[8]} {base_zynq_i/FifoManagerV4_0/U0/FIFO_Spare[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {base_zynq_i/FifoManagerV4_0/DataOut[0]} {base_zynq_i/FifoManagerV4_0/DataOut[1]} {base_zynq_i/FifoManagerV4_0/DataOut[2]} {base_zynq_i/FifoManagerV4_0/DataOut[3]} {base_zynq_i/FifoManagerV4_0/DataOut[4]} {base_zynq_i/FifoManagerV4_0/DataOut[5]} {base_zynq_i/FifoManagerV4_0/DataOut[6]} {base_zynq_i/FifoManagerV4_0/DataOut[7]} {base_zynq_i/FifoManagerV4_0/DataOut[8]} {base_zynq_i/FifoManagerV4_0/DataOut[9]} {base_zynq_i/FifoManagerV4_0/DataOut[10]} {base_zynq_i/FifoManagerV4_0/DataOut[11]} {base_zynq_i/FifoManagerV4_0/DataOut[12]} {base_zynq_i/FifoManagerV4_0/DataOut[13]} {base_zynq_i/FifoManagerV4_0/DataOut[14]} {base_zynq_i/FifoManagerV4_0/DataOut[15]} {base_zynq_i/FifoManagerV4_0/DataOut[16]} {base_zynq_i/FifoManagerV4_0/DataOut[17]} {base_zynq_i/FifoManagerV4_0/DataOut[18]} {base_zynq_i/FifoManagerV4_0/DataOut[19]} {base_zynq_i/FifoManagerV4_0/DataOut[20]} {base_zynq_i/FifoManagerV4_0/DataOut[21]} {base_zynq_i/FifoManagerV4_0/DataOut[22]} {base_zynq_i/FifoManagerV4_0/DataOut[23]} {base_zynq_i/FifoManagerV4_0/DataOut[24]} {base_zynq_i/FifoManagerV4_0/DataOut[25]} {base_zynq_i/FifoManagerV4_0/DataOut[26]} {base_zynq_i/FifoManagerV4_0/DataOut[27]} {base_zynq_i/FifoManagerV4_0/DataOut[28]} {base_zynq_i/FifoManagerV4_0/DataOut[29]} {base_zynq_i/FifoManagerV4_0/DataOut[30]} {base_zynq_i/FifoManagerV4_0/DataOut[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list base_zynq_i/FifoManagerV4_0/CLK]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
