# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/base_zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq || ORIG_REF_NAME==base_zynq} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_processing_system7_0_0} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==base_zynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_axi_dma_0_0/base_zynq_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_dma_0_0 || ORIG_REF_NAME==base_zynq_axi_dma_0_0} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_ps7_0_axi_periph_1/base_zynq_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_ps7_0_axi_periph_1 || ORIG_REF_NAME==base_zynq_ps7_0_axi_periph_1} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_axi_mem_intercon_0/base_zynq_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_mem_intercon_0 || ORIG_REF_NAME==base_zynq_axi_mem_intercon_0} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_xlconcat_0_0/base_zynq_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xlconcat_0_0 || ORIG_REF_NAME==base_zynq_xlconcat_0_0} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_xbar_0/base_zynq_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xbar_0 || ORIG_REF_NAME==base_zynq_xbar_0} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_AXIS_Test_Component_0_0/base_zynq_AXIS_Test_Component_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_AXIS_Test_Component_0_0 || ORIG_REF_NAME==base_zynq_AXIS_Test_Component_0_0} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_auto_pc_1/base_zynq_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_1 || ORIG_REF_NAME==base_zynq_auto_pc_1} -quiet] -quiet

# IP: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_auto_pc_0/base_zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_0 || ORIG_REF_NAME==base_zynq_auto_pc_0} -quiet] -quiet

# XDC: /home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/hw/bd/base_zynq/base_zynq_ooc.xdc
