# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jonathan/VivadoProjects/00_WATCHMANN/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xci
# IP: The module: 'base_zynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jonathan/VivadoProjects/00_WATCHMANN/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jonathan/VivadoProjects/00_WATCHMANN/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xci
# IP: The module: 'base_zynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jonathan/VivadoProjects/00_WATCHMANN/RealTB_AXI_Stream/hw/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
