# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/prototype_watchman_axi_smc_0.xci
# IP: The module: 'prototype_watchman_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/bd_a35b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_5/bd_a35b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_9/bd_a35b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_10/bd_a35b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_6/bd_a35b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_7/bd_a35b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_8/bd_a35b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_2/bd_a35b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_3/bd_a35b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_4/bd_a35b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_0/bd_a35b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_1/bd_a35b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_5/bd_a35b_s00a2s_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_9/bd_a35b_m00s2a_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_6/bd_a35b_sawn_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_7/bd_a35b_swn_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_8/bd_a35b_sbn_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_1/bd_a35b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_1/bd_a35b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prototype_watchman_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/prototype_watchman_axi_smc_0.xci
# IP: The module: 'prototype_watchman_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/bd_a35b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_5/bd_a35b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_9/bd_a35b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_10/bd_a35b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_6/bd_a35b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_7/bd_a35b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_8/bd_a35b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_2/bd_a35b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_3/bd_a35b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_4/bd_a35b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_0/bd_a35b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_1/bd_a35b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_5/bd_a35b_s00a2s_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_9/bd_a35b_m00s2a_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_6/bd_a35b_sawn_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_7/bd_a35b_swn_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_8/bd_a35b_sbn_0_ooc.xdc

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_1/bd_a35b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/bd_0/ip/ip_1/bd_a35b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/idlab-52/Desktop/GitVivado/Ky/WATCHMAN/Vivado_Projects/Test-Merge/Test_merge/prototype_watchman.srcs/sources_1/bd/prototype_watchman/ip/prototype_watchman_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prototype_watchman_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
