set_property SRC_FILE_INFO {cfile:/home/jonathan/GitProjects/WATCHMAN/Vivado_Projects/RealTB_AXI_Stream/XilinxBuild/RealTB_AXI_Stream.srcs/constrs_1/new/Constraint_RealTB.xdc rfile:../../../RealTB_AXI_Stream.srcs/constrs_1/new/Constraint_RealTB.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets base_zynq_i/AXIS_Test_Component_0/m00_axis_tlast]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_S00_AXI_inst/s00_axi_intr]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[7]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[11]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[31]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[22]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[27]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[26]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[6]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[3]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[9]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[14]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[15]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[18]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[19]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[23]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[28]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[0]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[17]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[1]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[12]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[13]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[8]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[29]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[16]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[20]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[21]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[24]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[2]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[4]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[10]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[30]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[5]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[25]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[20]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[15]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[18]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[11]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[29]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[12]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[11]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[22]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[14]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[8]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[28]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[0]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[30]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[23]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[15]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[21]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[30]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[1]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[3]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[22]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[7]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[31]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[27]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[16]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[25]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[6]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[0]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[23]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[8]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[10]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[3]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[4]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[5]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[9]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[26]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[20]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[4]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[6]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[28]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[13]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[24]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[25]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[27]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[17]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[19]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[12]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[14]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[1]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[19]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[13]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[9]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[7]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[21]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[16]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[17]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[24]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[26]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[29]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[2]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[31]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[2]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[5]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[10]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[18]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[4]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[0]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[1]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[11]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[13]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[15]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[17]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[18]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[16]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[14]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[12]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[2]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[3]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[5]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[6]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[7]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[8]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[27]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[29]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[31]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[30]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[28]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[19]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[21]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[23]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[25]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[26]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[24]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[22]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[20]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[9]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[10]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets base_zynq_i/axi_dma_0/U0/m_axi_s2mm_wlast]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_S00_AXI_inst/s00_axi_intr]]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[0]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[2]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[24]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[25]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[5]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[15]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[30]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[6]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[16]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[18]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[22]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[23]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[28]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[7]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[14]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[31]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[8]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[29]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[21]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[9]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[3]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[12]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[13]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[19]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[4]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[27]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[10]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[20]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[1]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[11]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[17]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[26]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[9]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[15]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[1]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[12]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[23]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[25]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[30]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[18]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[26]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[31]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[3]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[10]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[17]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[14]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[4]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[27]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[22]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[8]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[21]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[28]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[16]}]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[0]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[7]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[13]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[20]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[2]}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[5]}]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[6]}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[11]}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[19]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[24]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[29]}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_S00_AXI_inst_n_6]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_S00_AXI_inst_n_7]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list base_zynq_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[0]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[1]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[2]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[3]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[4]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[5]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[6]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[7]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[8]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[9]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[10]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[11]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[12]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[13]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[14]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[15]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[16]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[17]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[18]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[19]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[20]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[21]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[22]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[23]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[24]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[25]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[26]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[27]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[28]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[29]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[30]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/nbr_of_packets_s[31]}]]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[0]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[1]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[2]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[3]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[4]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[5]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[6]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[7]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[8]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[9]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[10]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[11]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[12]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[13]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[14]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[15]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[16]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[17]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[18]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[19]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[20]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[21]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[22]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[23]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[24]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[25]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[26]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[27]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[28]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[29]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[30]} {base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_M00_AXIS_inst/content_packet_s[31]}]]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[0]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[1]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[2]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[3]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[4]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[5]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[6]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[7]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[8]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[9]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[10]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[11]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[12]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[13]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[14]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[15]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[16]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[17]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[18]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[19]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[20]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[21]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[22]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[23]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[24]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[25]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[26]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[27]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[28]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[29]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[30]} {base_zynq_i/AXIS_Test_Component_0/U0/NBR_PACKETS[31]}]]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[0]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[1]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[2]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[3]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[4]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[5]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[6]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[7]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[8]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[9]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[10]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[11]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[12]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[13]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[14]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[15]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[16]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[17]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[18]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[19]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[20]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[21]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[22]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[23]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[24]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[25]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[26]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[27]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[28]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[29]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[30]} {base_zynq_i/AXIS_Test_Component_0/U0/CONTENT_1[31]}]]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[0]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[1]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[2]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[3]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[4]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[5]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[6]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[7]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[8]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[9]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[10]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[11]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[12]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[13]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[14]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[15]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[16]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[17]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[18]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[19]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[20]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[21]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[22]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[23]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[24]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[25]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[26]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[27]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[28]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[29]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[30]} {base_zynq_i/AXIS_Test_Component_0/m00_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[0]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[1]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[2]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[3]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[4]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[5]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[6]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[7]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[8]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[9]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[10]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[11]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[12]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[13]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[14]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[15]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[16]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[17]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[18]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[19]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[20]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[21]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[22]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[23]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[24]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[25]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[26]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[27]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[28]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[29]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[30]} {base_zynq_i/axi_dma_0/U0/s_axis_s2mm_tdata[31]}]]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_S00_AXI_inst_n_6]]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list base_zynq_i/AXIS_Test_Component_0/U0/AXIS_Peripheral_v1_0_S00_AXI_inst_n_7]]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list base_zynq_i/AXIS_Test_Component_0/m00_axis_tlast]]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list base_zynq_i/axi_dma_0/U0/m_axi_s2mm_wlast]]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
