#set_property MARK_DEBUG true [get_nets prototype_watchman_i/axi_dma_0_s2mm_introut]
#set_property MARK_DEBUG true [get_nets prototype_watchman_i/axi_dma_0_mm2s_introut]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[8]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[2]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[0]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[1]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[3]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[4]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[5]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[6]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[7]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[9]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[10]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[12]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[14]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[16]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[18]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[19]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[17]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[15]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[13]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[11]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[26]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[21]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[20]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[22]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[23]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[24]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[25]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[29]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[30]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[27]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[31]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tdata[28]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tkeep[0]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tkeep[1]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tkeep[2]}]
#set_property MARK_DEBUG true [get_nets {prototype_watchman_i/axi_dma_0/s_axis_s2mm_tkeep[3]}]
#set_property MARK_DEBUG true [get_nets prototype_watchman_i/axi_dma_0/s_axis_s2mm_tlast]
#set_property MARK_DEBUG true [get_nets prototype_watchman_i/axi_dma_0/s_axis_s2mm_tready]
#set_property MARK_DEBUG true [get_nets prototype_watchman_i/axi_dma_0/s_axis_s2mm_tvalid]
#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list prototype_watchman_i/processing_system7_0/inst/FCLK_CLK0]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 32 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {prototype_watchman_i/example_0/A_TDATA[0]} {prototype_watchman_i/example_0/A_TDATA[1]} {prototype_watchman_i/example_0/A_TDATA[2]} {prototype_watchman_i/example_0/A_TDATA[3]} {prototype_watchman_i/example_0/A_TDATA[4]} {prototype_watchman_i/example_0/A_TDATA[5]} {prototype_watchman_i/example_0/A_TDATA[6]} {prototype_watchman_i/example_0/A_TDATA[7]} {prototype_watchman_i/example_0/A_TDATA[8]} {prototype_watchman_i/example_0/A_TDATA[9]} {prototype_watchman_i/example_0/A_TDATA[10]} {prototype_watchman_i/example_0/A_TDATA[11]} {prototype_watchman_i/example_0/A_TDATA[12]} {prototype_watchman_i/example_0/A_TDATA[13]} {prototype_watchman_i/example_0/A_TDATA[14]} {prototype_watchman_i/example_0/A_TDATA[15]} {prototype_watchman_i/example_0/A_TDATA[16]} {prototype_watchman_i/example_0/A_TDATA[17]} {prototype_watchman_i/example_0/A_TDATA[18]} {prototype_watchman_i/example_0/A_TDATA[19]} {prototype_watchman_i/example_0/A_TDATA[20]} {prototype_watchman_i/example_0/A_TDATA[21]} {prototype_watchman_i/example_0/A_TDATA[22]} {prototype_watchman_i/example_0/A_TDATA[23]} {prototype_watchman_i/example_0/A_TDATA[24]} {prototype_watchman_i/example_0/A_TDATA[25]} {prototype_watchman_i/example_0/A_TDATA[26]} {prototype_watchman_i/example_0/A_TDATA[27]} {prototype_watchman_i/example_0/A_TDATA[28]} {prototype_watchman_i/example_0/A_TDATA[29]} {prototype_watchman_i/example_0/A_TDATA[30]} {prototype_watchman_i/example_0/A_TDATA[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 32 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {prototype_watchman_i/example_0/B_TDATA[0]} {prototype_watchman_i/example_0/B_TDATA[1]} {prototype_watchman_i/example_0/B_TDATA[2]} {prototype_watchman_i/example_0/B_TDATA[3]} {prototype_watchman_i/example_0/B_TDATA[4]} {prototype_watchman_i/example_0/B_TDATA[5]} {prototype_watchman_i/example_0/B_TDATA[6]} {prototype_watchman_i/example_0/B_TDATA[7]} {prototype_watchman_i/example_0/B_TDATA[8]} {prototype_watchman_i/example_0/B_TDATA[9]} {prototype_watchman_i/example_0/B_TDATA[10]} {prototype_watchman_i/example_0/B_TDATA[11]} {prototype_watchman_i/example_0/B_TDATA[12]} {prototype_watchman_i/example_0/B_TDATA[13]} {prototype_watchman_i/example_0/B_TDATA[14]} {prototype_watchman_i/example_0/B_TDATA[15]} {prototype_watchman_i/example_0/B_TDATA[16]} {prototype_watchman_i/example_0/B_TDATA[17]} {prototype_watchman_i/example_0/B_TDATA[18]} {prototype_watchman_i/example_0/B_TDATA[19]} {prototype_watchman_i/example_0/B_TDATA[20]} {prototype_watchman_i/example_0/B_TDATA[21]} {prototype_watchman_i/example_0/B_TDATA[22]} {prototype_watchman_i/example_0/B_TDATA[23]} {prototype_watchman_i/example_0/B_TDATA[24]} {prototype_watchman_i/example_0/B_TDATA[25]} {prototype_watchman_i/example_0/B_TDATA[26]} {prototype_watchman_i/example_0/B_TDATA[27]} {prototype_watchman_i/example_0/B_TDATA[28]} {prototype_watchman_i/example_0/B_TDATA[29]} {prototype_watchman_i/example_0/B_TDATA[30]} {prototype_watchman_i/example_0/B_TDATA[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 1 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list prototype_watchman_i/axi_dma_0_mm2s_introut]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 1 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list prototype_watchman_i/axi_dma_0_s2mm_introut]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 1 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list prototype_watchman_i/axi_dma_0/m_axi_mm2s_rlast]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 1 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list prototype_watchman_i/axi_dma_0/m_axi_mm2s_rready]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 1 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list prototype_watchman_i/axi_dma_0/m_axi_mm2s_rvalid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 1 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list prototype_watchman_i/axi_dma_0/m_axis_mm2s_tlast]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 1 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list prototype_watchman_i/axi_dma_0/m_axis_mm2s_tready]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
#set_property port_width 1 [get_debug_ports u_ila_0/probe9]
#connect_debug_port u_ila_0/probe9 [get_nets [list prototype_watchman_i/axi_dma_0/m_axis_mm2s_tvalid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
#set_property port_width 1 [get_debug_ports u_ila_0/probe10]
#connect_debug_port u_ila_0/probe10 [get_nets [list prototype_watchman_i/axi_dma_0/s_axis_s2mm_tlast]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
#set_property port_width 1 [get_debug_ports u_ila_0/probe11]
#connect_debug_port u_ila_0/probe11 [get_nets [list prototype_watchman_i/axi_dma_0/s_axis_s2mm_tready]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
#set_property port_width 1 [get_debug_ports u_ila_0/probe12]
#connect_debug_port u_ila_0/probe12 [get_nets [list prototype_watchman_i/axi_dma_0/s_axis_s2mm_tvalid]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
